stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest
  
maven-build:
    stage: mavenbuild
    tags:
      - BACKEND
    script:
      - cd Backend/gatsby
      - mvn package -B

maven-test:
    stage: maventest
    tags:
      - BACKEND
    script:
      - cd Backend/gatsby
      - mvn test
      - mvn package -B
    artifacts:
      paths:
        - Backend/gatsby/target/*.jar

autoDeploy:
  stage: autodeploy
  tags: 
    - BACKEND
  script: 
    - cd Backend/gatsby
    - mvn test
    - mvn package -B
    - sudo mv target/*.jar /target/gatsby.jar
    - sudo systemctl stop gatsby
    - sudo systemctl start gatsby
android-build:    
    image: javiersantos/android-ci:latest
    stage: androidbuild    
    before_script:        
        - export GRADLE_USER_HOME='pwd'/.gradle        
        - chmod +x ./Frontend/Gatsby/gradlew    
    tags:        
        - FRONTEND    
    script:        
        - cd Frontend/Gatsby/
        - ./gradlew assemble
    artifacts:
        paths:
            - Frontend/Gatsby/app/build/outputs/
unitTests:
    image: javiersantos/android-ci:latest    
    stage: androidtest    
    before_script:        
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./Frontend/Gatsby/gradlew
    tags:        
        - FRONTEND    
    script:        
        - cd Frontend/Gatsby/
        - ./gradlew assemble        