stages:
  - mavenbuild
  - maventest
  - autodeploy
  
maven-build:
    stage: mavenbuild
    tags:
      - BACKEND
    script:
      - cd Backend/gatsby
      - mvn package -B

maven-test:
    stage: maventest
    tags:
      - BACKEND
    script:
      - cd Backend/gatsby
      - mvn test
      - mvn package -B
    artifacts:
      paths:
        - Backend/gatsby/target/*.jar

autoDeploy:
  stage: autodeploy
  tags: 
    - BACKEND
  script: 
    - cd Backend/gatsby
    - mvn test
    - mvn package -B
    - sudo mv target/*.jar /target/gatsby.jar
    - sudo systemctl stop gatsby
    - sudo systemctl start gatsby